### PR TITLE
README: Adding dart-multihash package link

### PR DESCRIPTION
**Pull request by LuchoTurtle**
Adding the [`dart_multihash`](https://github.com/dwyl/dart_multihash) dart-lang package to the implementations list.

### CODE REVIEW

**Comment by nelsonic** [comment]
Stoked that the addition was accepted. 🎉 
But shouldn't the order of implementations be ***Alphabetical*** by programming language? 🔤 🤷‍♂️ 
image

Or is this just an "Append To List" without sorting? 😜 
Would a PR re-ordering the list be accepted/merged? 💭 
Am I just manifesting "OCD"? 🙄

**Comment by vmx** [comment]
> Would a PR re-ordering the list be accepted/merged? thought_balloon

I would happily accept such a PR. Looking it at, there also seem to be multiple of the same language (e.g. C#). It would be great if you would bundle them like e.g. the python or rust ones.

**Comment by nelsonic** [comment]
@vmx Coming right up! 🧑‍💻 ⏳

**Comment by nelsonic** [comment]
PR: https://github.com/multiformats/multihash/pull/155 :shipit:

**Pull request merged**
