### PR TITLE
Add MD4,MD5; add warning about obsolete hash functions

### LINKED ISSUE #71: Add MD5 (and MD4?)
We should add MD5 and MD4 just because tons of people are still using these and we should help them upgrade. these are **non cryptographic hashes** now. As per http://multiformats.io/multihash/#what-about-non-cryptographic-hashes-like-murmur3-cityhash-etc

### PR DESCRIPTION
**Pull request by celeduc**
Resolves #71 by adding MD4 and MD5 to the list of supported hash functions.

Adds a note to the README cautioning about their use.

### CODE REVIEW

**Comment by celeduc** [comment]
@jbenet could you please look this over? I'm actually in need of this functionality.

**Comment by lgierth** [comment]
I think these codes look good to me, what do you think @diasdavid @whyrusleeping 

@celeduc could you also add these to the csv in multicodec? That one is the canonical table and multihash is just a subset. I dislike the duplication too, PRs very welcome :)

**Comment by diasdavid** [comment]
Seems that there is no collision with https://github.com/multiformats/multicodec/blob/master/table.csv, as @lgierth said, we prefer to have the codecs first merged at the multicodec table then on the specs that dependent on it, so once we have that, we are golden to merge all of them PRs :)

**Comment by celeduc** [comment]
I submitted [PR #41 to multicodec](https://github.com/multiformats/multicodec/issues/41), where it's held with [a comment by](https://github.com/multiformats/multicodec/pull/41#issuecomment-284218125) @Kubuxu

**Comment by celeduc** [comment]
Ready for merge!

**Comment by diasdavid** [comment]
thank you @celeduc :)

**Pull request merged**
