### PR TITLE
Add link to net-ipfs-core

### PR DESCRIPTION
**Pull request by richardschneider**

### CODE REVIEW

**Comment by RichardLitt** [comment]
Would it be possible to split net-ipfs-core into different packages?

**Comment by richardschneider** [comment]
Anything is possible, but I prefer to keep things together.  This is the ,Net way.

**Comment by tabrath** [comment]
@richardschneider It might have been "the .net way" to maintain mono-repos, but many (including Microsoft) has adopted to smaller repos or atleast small assemblies with less responsibilities. But hey, that's your decision :) For me it's certainly not "the .net way" to go.

**Comment by RichardLitt** [comment]
There's no issue with linking to multiple implementations. Given that, I am going to merge this; if someone wants to split it out later, we can link to that package too. Thank you, @richardschneider.

**Pull request merged**
